In [6]:
#Implementation of Gradient Descent using tensorflow
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

In [8]:
df=pd.read_csv("insurance_data.csv")
df.head()

   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=25)

#scaling for better accuracy and less error rate
X_train_scaled=X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100

X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100

In [ ]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy'])
model.fit(X_train_scaled,y_train,epochs=5000)

Epoch 1/5000

E0000 00:00:1772966634.359798    7088 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 532ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7072
Epoch 13/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.7068
Epoch 14/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.7065
Epoch 15/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.7061
Epoch 16/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.7057
Epoch 17/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7054
Epoch 18/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7050
Epoch 19/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7046
Epoch 20/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.7043
Epoch 21/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.7039
Epoch 22/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5000 - loss: 0.7035
Epoch 23/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5000 - loss: 0.7032
Epoch 24/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.7028
Epoch 25/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5000 - loss: 0.7025
Epoch 26/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7021
Epoch 27/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7017
Epoch 28/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7014
Epoch 29/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.7010
Epoch 30/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7007
Epoch 31/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.7003
Epoch 32/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7000
Epoch 33/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.5000 - loss: 0.6996
Epoch 34/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6993
Epoch 35/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6989
Epoch 36/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6986
Epoch 37/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6982
Epoch 38/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6979
Epoch 39/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6975
Epoch 40/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6972
Epoch 41/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6969
Epoch 42/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6965
Epoch 43/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6962
Epoch 44/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6958
Epoch 45/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6955
Epoch 46/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6952
Epoch 47/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6948
Epoch 48/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.5000 - loss: 0.6945
Epoch 49/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5000 - loss: 0.6942
Epoch 50/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6938
Epoch 51/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6935
Epoch 52/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6932
Epoch 53/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6928
Epoch 54/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6925
Epoch 55/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6922
Epoch 56/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6918
Epoch 57/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.6915
Epoch 58/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.5000 - loss: 0.6912
Epoch 59/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.5000 - loss: 0.6909
Epoch 60/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6906
Epoch 61/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6902
Epoch 62/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6899
Epoch 63/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6896
Epoch 64/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6893
Epoch 65/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6890
Epoch 66/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6886
Epoch 67/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6883
Epoch 68/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6880
Epoch 69/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6877
Epoch 70/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.5000 - loss: 0.6874
Epoch 71/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5000 - loss: 0.6871
Epoch 72/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5000 - loss: 0.6868
Epoch 73/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 0.5000 - loss: 0.6865
Epoch 74/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6862
Epoch 75/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.6859
Epoch 76/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6856
Epoch 77/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6853
Epoch 78/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6849
Epoch 79/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6846
Epoch 80/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6843
Epoch 81/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.5000 - loss: 0.6840
Epoch 82/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.5000 - loss: 0.6838
Epoch 83/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5000 - loss: 0.6835
Epoch 84/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5000 - loss: 0.6832
Epoch 85/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6829
Epoch 86/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6826
Epoch 87/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6823
Epoch 88/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 0.5000 - loss: 0.6820
Epoch 89/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6817
Epoch 90/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6814
Epoch 91/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6811
Epoch 92/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6808
Epoch 93/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6805
Epoch 94/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6803
Epoch 95/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6800
Epoch 96/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6797
Epoch 97/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6794
Epoch 98/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6791
Epoch 99/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6788
Epoch 100/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6786
Epoch 101/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6783
Epoch 102/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.6780
Epoch 103/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5000 - loss: 0.6777
Epoch 104/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5000 - loss: 0.6775
Epoch 105/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6772
Epoch 106/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6769
Epoch 107/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6766
Epoch 108/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6764
Epoch 109/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6761
Epoch 110/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6758
Epoch 111/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6756
Epoch 112/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6753
Epoch 113/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6750
Epoch 114/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6748
Epoch 115/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6745
Epoch 116/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6742
Epoch 117/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6740
Epoch 118/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6737
Epoch 119/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6735
Epoch 120/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5000 - loss: 0.6732
Epoch 121/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5000 - loss: 0.6730
Epoch 122/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6727
Epoch 123/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6724
Epoch 124/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6722
Epoch 125/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6719
Epoch 126/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6717
Epoch 127/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6714
Epoch 128/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6712
Epoch 129/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6709
Epoch 130/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6707
Epoch 131/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6704
Epoch 132/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6702
Epoch 133/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6699
Epoch 134/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6697
Epoch 135/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6695
Epoch 136/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.5000 - loss: 0.6692
Epoch 137/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.6690
Epoch 138/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6687
Epoch 139/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6685
Epoch 140/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6683
Epoch 141/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6680
Epoch 142/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6678
Epoch 143/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6675
Epoch 144/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6673
Epoch 145/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6671
Epoch 146/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6668
Epoch 147/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6666
Epoch 148/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6664
Epoch 149/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6661
Epoch 150/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6659
Epoch 151/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6657
Epoch 152/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6655
Epoch 153/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6652
Epoch 154/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.6650
Epoch 155/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6648
Epoch 156/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6646
Epoch 157/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6643
Epoch 158/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6641
Epoch 159/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6639
Epoch 160/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6637
Epoch 161/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6635
Epoch 162/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6632
Epoch 163/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6630
Epoch 164/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6628
Epoch 165/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6626
Epoch 166/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6624
Epoch 167/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6622
Epoch 168/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6620
Epoch 169/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6617
Epoch 170/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6615
Epoch 171/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6613
Epoch 172/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - accuracy: 0.5000 - loss: 0.6611
Epoch 173/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5455 - loss: 0.6609
Epoch 174/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5455 - loss: 0.6607
Epoch 175/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5455 - loss: 0.6605
Epoch 176/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5455 - loss: 0.6603
Epoch 177/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5455 - loss: 0.6601
Epoch 178/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5455 - loss: 0.6599
Epoch 179/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5455 - loss: 0.6597
Epoch 180/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5455 - loss: 0.6595
Epoch 181/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6593
Epoch 182/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6591
Epoch 183/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5455 - loss: 0.6589
Epoch 184/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6587
Epoch 185/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5455 - loss: 0.6585
Epoch 186/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5455 - loss: 0.6583
Epoch 187/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5455 - loss: 0.6581
Epoch 188/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6579
Epoch 189/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5455 - loss: 0.6577
Epoch 190/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.5455 - loss: 0.6575
Epoch 191/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5455 - loss: 0.6573
Epoch 192/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.6571
Epoch 193/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5455 - loss: 0.6569
Epoch 194/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5455 - loss: 0.6568
Epoch 195/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5455 - loss: 0.6566
Epoch 196/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5455 - loss: 0.6564
Epoch 197/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5455 - loss: 0.6562
Epoch 198/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.6560
Epoch 199/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5455 - loss: 0.6558
Epoch 200/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6556
Epoch 201/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6555
Epoch 202/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6553
Epoch 203/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5455 - loss: 0.6551
Epoch 204/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5455 - loss: 0.6549
Epoch 205/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5455 - loss: 0.6547
Epoch 206/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5455 - loss: 0.6545
Epoch 207/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.6544
Epoch 208/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5455 - loss: 0.6542
Epoch 209/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.5455 - loss: 0.6540
Epoch 210/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5455 - loss: 0.6538
Epoch 211/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6537
Epoch 212/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6535
Epoch 213/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5455 - loss: 0.6533
Epoch 214/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5455 - loss: 0.6531
Epoch 215/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5455 - loss: 0.6530
Epoch 216/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5455 - loss: 0.6528
Epoch 217/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5455 - loss: 0.6526
Epoch 218/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5455 - loss: 0.6525
Epoch 219/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5455 - loss: 0.6523
Epoch 220/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6521
Epoch 221/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6519
Epoch 222/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6518
Epoch 223/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5455 - loss: 0.6516
Epoch 224/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6515
Epoch 225/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5455 - loss: 0.6513
Epoch 226/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5455 - loss: 0.6511
Epoch 227/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5455 - loss: 0.6510
Epoch 228/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5455 - loss: 0.6508
Epoch 229/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5455 - loss: 0.6506
Epoch 230/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5455 - loss: 0.6505
Epoch 231/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5455 - loss: 0.6503
Epoch 232/5000

model.evaluate(X_test_scaled,y_test)

In [19]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.3550

[0.35497763752937317, 1.0]

In [20]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [23]:
coef, intercept=model.get_weights()

In [24]:
coef, intercept

(array([[5.0608625],
        [1.408652 ]], dtype=float32),
 array([-2.9137027], dtype=float32))

here w1=5.0608 and w2=1.4086 and bias=-2.913

Implementation of Gradient DEscent without uisng tensorflow keras

In [25]:
def sigmoid(x):
    import math
    return 1/(1+math.exp(-x))
sigmoid(18)

0.9999999847700205

In [26]:
X_test

    age  affordibility
2    47              1
10   18              1
21   26              0
11   28              1
14   49              1
9    61              1

In [27]:
def prediction_function(age,affordibility):
    weighted_sum=coef[0]*age+coef[1]*affordibility+intercept
    return sigmoid(weighted_sum)
prediction_function(.47,1)

/tmp/ipykernel_7088/574919516.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))

0.7054847702382996

In [30]:
def sigmoid_numpy(X):
    return 1/(1+np.exp(-X))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [32]:
def log_loss(y_true,y_predicted):
    epsilon=1e-15
    y_predicted_new=[max(i,epsilon) for i in y_predicted]
    y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [35]:
def gradient_descent(age,affordibility,y_true,epochs,loss_threshold):
    w1=w2=0
    bias=0
    rate=0.5
    n=len(age)
    for i in range(epochs):
        weighted_sum=w1*age+w2*affordibility+bias
        y_predicted=sigmoid_numpy(weighted_sum)
        loss=log_loss(y_true,y_predicted)

        w1d=(1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
        w2d=(1/n)*np.dot(np.transpose(affordibility),(y_predicted-y_true))

        bias_d=np.mean(y_predicted-y_true)
        w1=w1-rate*w1d
        w2=w2-rate*w2d
        bias=bias-rate*bias_d

        print(f'Epoch:{i},w1:{w1},w2:{w2},bias:{bias},loss:{loss}')

        if loss<=loss_threshold:
            break
    return w1,w2,bias

In [37]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,1000,0.4631)

Epoch:0,w1:0.024318181818181826,w2:0.045454545454545456,bias:0.0,loss:0.6931471805599453
Epoch:1,w1:0.046532101759595226,w2:0.08647105225023963,bias:-0.004841495282008105,loss:0.6880851350148476
Epoch:2,w1:0.06708738929577727,w2:0.123863596911539,bias:-0.013455423643272062,loss:0.6838539043604727
Epoch:3,w1:0.08633804668084633,w2:0.1582818726587562,bias:-0.024993103907863065,loss:0.6801769512884495
Epoch:4,w1:0.10456450468395169,w2:0.19024321720378462,bias:-0.03878266341920814,loss:0.6768786343273759
Epoch:5,w1:0.12198861288216892,w2:0.22015943486833162,bias:-0.05429295760984407,loss:0.673847150675346
Epoch:6,w1:0.13878577300913103,w2:0.24835860186955866,bias:-0.07110440662581538,loss:0.6710109783986781
Epoch:7,w1:0.15509462872883883,w2:0.2751025150492992,bias:-0.08888572163473854,loss:0.6683239981162274
Epoch:8,w1:0.17102475084873503,w2:0.3006005395908055,bias:-0.10737545129278292,loss:0.665756123870844
Epoch:9,w1:0.1866627131473239,w2:0.325020554821465,bias:-0.1263673932992857,loss:0.6632874084429674
Epoch:10,w1:0.20207689033307955,w2:0.3484975922401574,bias:-0.145699072975211,loss:0.6609043337049987
Epoch:11,w1:0.21732124679622586,w2:0.3711406504197008,bias:-0.16524264347124792,loss:0.658597474028661
Epoch:12,w1:0.23243833006976244,w2:0.39303807390021656,bias:-0.18489769429567135,loss:0.6563600227506128
Epoch:13,w1:0.247461637840841,w2:0.4142618019895111,bias:-0.2045855632316951,loss:0.6541868615817086
Epoch:14,w1:0.26241749126076275,w2:0.4348707280000528,bias:-0.2242448333341951,loss:0.6520739719435202
Epoch:15,w1:0.2773265188027929,w2:0.4549133576847187,bias:-0.24382776502364667,loss:0.6500180618835281
Epoch:16,w1:0.2922048325607817,w2:0.474429914988127,bias:-0.26329746687045386,loss:0.6480163290604916
Epoch:17,w1:0.3070649613866671,w2:0.4934540114298735,bias:-0.28262565058280825,loss:0.646066309707072
Epoch:18,w1:0.3219165915763742,w2:0.5120139705765295,bias:-0.3017908485131625,loss:0.6441657819735477
Epoch:19,w1:0.3367671550921366,w2:0.5301338796136434,bias:-0.32077699769562384,loss:0.6423127037026214
Epoch:20,w1:0.35162229689825514,w2:0.547834424797334,bias:-0.339572314591756,loss:0.6405051720271867
Epoch:21,w1:0.3664862463770147,w2:0.56513355561402,bias:-0.35816840057545146,loss:0.6387413968165261
Epoch:22,w1:0.3813621125871351,w2:0.582047013083338,bias:-0.37655953067318626,loss:0.6370196829236816
Epoch:23,w1:0.3962521190229128,w2:0.5985887502435739,bias:-0.39474208792575877,loss:0.6353384180376105
Epoch:24,w1:0.41115779029077004,w2:0.61477126702709,bias:-0.412714113519467,loss:0.6336960641149078
Epoch:25,w1:0.42608010055657847,w2:0.6306058771282184,bias:-0.43047494899064703,loss:0.632091151107361
Epoch:26,w1:0.4410195915877561,w2:0.6461029208254572,bias:-0.44802495168262824,loss:0.6305222721713198
Epoch:27,w1:0.45597646660598956,w2:0.6612719348385593,bias:-0.46536526849855575,loss:0.6289880798424942
Epoch:28,w1:0.4709506648910526,w2:0.6761217880188242,bias:-0.4824976560591521,loss:0.6274872828484654
Epoch:29,w1:0.4859419210640327,w2:0.690660789861675,bias:-0.49942433780806644,loss:0.6260186433507784
Epoch:30,w1:0.5009498121745475,w2:0.7048967773954379,bias:-0.5161478905403953,loss:0.6245809744843017
Epoch:31,w1:0.5159737950779952,w2:0.7188371848611625,bias:-0.5326711543659843,loss:0.6231731381095799
Epoch:32,w1:0.5310132360813753,w2:0.7324890996938072,bias:-0.5489971613402505,loss:0.6217940427243497
Epoch:33,w1:0.5460674344326882,w2:0.7458593075965555,bias:-0.5651290789664077,loss:0.6204426414996497
Epoch:34,w1:0.561135640907983,w2:0.7589543289290053,bias:-0.5810701655455637,loss:0.6191179304181499
Epoch:35,w1:0.5762170724947732,w2:0.7717804481760258,bias:-0.596823734965956,loss:0.6178189465000182
Epoch:36,w1:0.5913109239673421,w2:0.7843437379031284,bias:-0.6123931290119771,loss:0.6165447661064983
Epoch:37,w1:0.6064163769877033,w2:0.7966500783171045,bias:-0.6277816956632698,loss:0.6152945033144225
Epoch:38,w1:0.6215326072371999,w2:0.8087051733222952,bias:-0.6429927721644798,loss:0.6140673083568076
Epoch:39,w1:0.636658789981165,w2:0.8205145637811389,bias:-0.6580296718934238,loss:0.6128623661258701
Epoch:40,w1:0.6517941043873742,w2:0.8320836385430247,bias:-0.6728956742523713,loss:0.611678894735555
Epoch:41,w1:0.6669377368539374,w2:0.8434176436903804,bias:-0.687594016964081,loss:0.6105161441411315
Epoch:42,w1:0.6820888835504145,w2:0.8545216903593014,bias:-0.7021278902793336,loss:0.6093733948137079
Epoch:43,w1:0.6972467523346059,w2:0.8654007614190938,bias:-0.7165004327024445,loss:0.6082499564676914
Epoch:44,w1:0.7124105641745203,w2:0.8760597172370368,bias:-0.7307147279207776,loss:0.6071451668393485
Epoch:45,w1:0.7275795541787512,w2:0.886503300708441,bias:-0.7447738026877283,loss:0.6060583905146887
Epoch:46,w1:0.7427529723175439,w2:0.896736141695277,bias:-0.7586806254592534,loss:0.6049890178049557
Epoch:47,w1:0.7579300839001307,w2:0.906762760987348,bias:-0.7724381056244243,loss:0.6039364636680574
Epoch:48,w1:0.773110169860581,w2:0.9165875738766525,bias:-0.7860490932027137,loss:0.6029001666742926
Epoch:49,w1:0.7882925268937837,w2:0.9262148934170268,bias:-0.7995163789064665,loss:0.6018795880147816
Epoch:50,w1:0.8034764674746953,w2:0.9356489334263742,bias:-0.8128426944875573,loss:0.600874210551025
Epoch:51,w1:0.8186613197872172,w2:0.9448938112770402,bias:-0.8260307133036503,loss:0.5998835379040659
Epoch:52,w1:0.8338464275836664,w2:0.9539535505105408,bias:-0.8390830510525951,loss:0.598907093581754
Epoch:53,w1:0.84903114999149,w2:0.9628320833054217,bias:-0.8520022666339631,loss:0.5979444201426523
Epoch:54,w1:0.8642148612804359,w2:0.9715332528211148,bias:-0.8647908631051062,loss:0.5969950783951655
Epoch:55,w1:0.8793969506006466,w2:0.9800608154359709,bias:-0.8774512887058117,loss:0.5960586466305067
Epoch:56,w1:0.8945768216999513,w2:0.9884184428939217,bias:-0.8899859379309735,loss:0.5951347198881556
Epoch:57,w1:0.9097538926268857,w2:0.996609724371272,bias:-0.9023971526349815,loss:0.5942229092525096
Epoch:58,w1:0.924927595424573,w2:1.004638168472783,bias:-0.9146872231549461,loss:0.5933228411794638
Epoch:59,w1:0.940097375819492,w2:1.0125072051643536,bias:-0.9268583894426087,loss:0.5924341568516938
Epoch:60,w1:0.9552626929082668,w2:1.0202201876481467,bias:-0.9389128421969778,loss:0.5915565115614702
Epoch:61,w1:0.9704230188449141,w2:1.027780394184848,bias:-0.9508527239914732,loss:0.5906895741198537
Epoch:62,w1:0.9855778385304176,w2:1.0351910298668348,bias:-0.9626801303907578,loss:0.5898330262911785
Epoch:63,w1:1.0007266493060551,w2:1.042455228345318,bias:-0.9743971110535526,loss:0.5889865622517612
Epoch:64,w1:1.0158689606515505,w2:1.0495760535139567,bias:-0.9860056708186191,loss:0.5881498880718119
Epoch:65,w1:1.0310042938888377,w2:1.056556501151004,bias:-0.9975077707718039,loss:0.587322721219569
Epoch:66,w1:1.0461321818920093,w2:1.063399500521701,bias:-1.0089053292926067,loss:0.5865047900867082
Epoch:67,w1:1.061252168803838,w2:1.0701079159423659,bias:-1.0202002230791822,loss:0.58569583353412
Epoch:68,w1:1.07636380975913,w2:1.0766845483074203,bias:-1.0313942881510447,loss:0.5848956004571799
Epoch:69,w1:1.0914666706150515,w2:1.083132136580433,bias:-1.0424893208290278,loss:0.5841038493696771
Epoch:70,w1:1.1065603276884992,w2:1.089453359250136,bias:-1.0534870786922765,loss:0.5833203480055918
Epoch:71,w1:1.1216443675005026,w2:1.0956508357522805,bias:-1.0643892815122233,loss:0.582544872937956
Epoch:72,w1:1.1367183865276125,w2:1.1017271278581156,bias:-1.0751976121636406,loss:0.5817772092140507
Epoch:73,w1:1.1517819909601816,w2:1.107684741030233,bias:-1.0859137175129692,loss:0.5810171500062391
Epoch:74,w1:1.1668347964674182,w2:1.1135261257464684,bias:-1.0965392092842026,loss:0.580264496277744
Epoch:75,w1:1.1818764279690706,w2:1.1192536787925202,bias:-1.107075664902678,loss:0.5795190564627322
Epoch:76,w1:1.1969065194135902,w2:1.124869744523932,bias:-1.1175246283171625,loss:0.5787806461600722
Epoch:77,w1:1.2119247135626037,w2:1.1303766160980537,bias:-1.127887610800666,loss:0.5780490878401724
Epoch:78,w1:1.2269306617815237,w2:1.1357765366765957,bias:-1.138166091730437,loss:0.5773242105643288
Epoch:79,w1:1.2419240238361193,w2:1.1410717005993707,bias:-1.1483615193476115,loss:0.5766058497160351
Epoch:80,w1:1.2569044676948726,w2:1.1462642545298152,bias:-1.1584753114969963,loss:0.5758938467437303
Epoch:81,w1:1.2718716693369392,w2:1.1513562985728742,bias:-1.168508856347478,loss:0.5751880489144875
Epoch:82,w1:1.2868253125655393,w2:1.1563498873658262,bias:-1.1784635130935468,loss:0.574488309078162
Epoch:83,w1:1.3017650888266064,w2:1.161247031142621,bias:-1.1883406126384257,loss:0.5737944854415423
Epoch:84,w1:1.3166906970325216,w2:1.1660496967723,bias:-1.1981414582592878,loss:0.5731064413520679
Epoch:85,w1:1.3316018433907708,w2:1.1707598087720583,bias:-1.2078673262550437,loss:0.5724240450906933
Epoch:86,w1:1.3464982412373603,w2:1.1753792502955096,bias:-1.2175194665771714,loss:0.5717471696735007
Epoch:87,w1:1.3613796108748355,w2:1.1799098640967038,bias:-1.2270991034440522,loss:0.5710756926616765
Epoch:88,w1:1.3762456794147504,w2:1.1843534534704454,bias:-1.2366074359392676,loss:0.570409495979491
Epoch:89,w1:1.3910961806244406,w2:1.188711783169452,bias:-1.2460456385943033,loss:0.5697484657399275
Epoch:90,w1:1.4059308547779577,w2:1.1929865802988897,bias:-1.2554148619560948,loss:0.5690924920776304
Epoch:91,w1:1.4207494485110257,w2:1.1971795351888097,bias:-1.2647162331398392,loss:0.5684414689888513
Epoch:92,w1:1.435551714679891,w2:1.20129230224501,bias:-1.273950856367487,loss:0.5677952941780915
Epoch:93,w1:1.4503374122239334,w2:1.205326500778833,bias:-1.2831198134923185,loss:0.5671538689111478
Epoch:94,w1:1.465106306031917,w2:1.209283715816406,bias:-1.2922241645099943,loss:0.5665170978742838
Epoch:95,w1:1.4798581668117623,w2:1.2131654988878222,bias:-1.3012649480564646,loss:0.5658848890392605
Epoch:96,w1:1.4945927709637252,w2:1.2169733687967492,bias:-1.310243181893107,loss:0.5652571535339768
Epoch:97,w1:1.50930990045687,w2:1.22070881237095,bias:-1.319159863379454,loss:0.564633805518469
Epoch:98,w1:1.5240093427087344,w2:1.2243732851941853,bias:-1.328015969933859,loss:0.564014762066048
Epoch:99,w1:1.538690890468081,w2:1.2279682123199616,bias:-1.3368124594824453,loss:0.5633999430493423
Epoch:100,w1:1.5533543417006375,w2:1.2314949889675804,bias:-1.3455502708966633,loss:0.5627892710310449
Epoch:101,w1:1.5679994994777327,w2:1.234954981200934,bias:-1.3542303244197815,loss:0.5621826711591541
Epoch:102,w1:1.5826261718677341,w2:1.2383495265904825,bias:-1.3628535220826186,loss:0.5615800710665213
Epoch:103,w1:1.5972341718302014,w2:1.241679934858842,bias:-1.3714207481088228,loss:0.5609814007745164
Epoch:104,w1:1.6118233171126706,w2:1.2449474885104017,bias:-1.3799328693099893,loss:0.5603865926006387
Epoch:105,w1:1.626393430149986,w2:1.2481534434453756,bias:-1.3883907354709002,loss:0.5597955810699011
Epoch:106,w1:1.6409443379661053,w2:1.2512990295586952,bias:-1.396795179725165,loss:0.559208302829829
Epoch:107,w1:1.6554758720782965,w2:1.2543854513241277,bias:-1.4051470189215274,loss:0.5586246965689197
Epoch:108,w1:1.6699878684036589,w2:1.2574138883640056,bias:-1.4134470539811,loss:0.5580447029384134
Epoch:109,w1:1.6844801671678955,w2:1.2603854960049383,bias:-1.4216960702457768,loss:0.5574682644772382
Epoch:110,w1:1.6989526128162689,w2:1.2633014058198724,bias:-1.4298948378180714,loss:0.556895325539993
Epoch:111,w1:1.7134050539266772,w2:1.2661627261568529,bias:-1.4380441118926133,loss:0.5563258322278385
Epoch:112,w1:1.7278373431247847,w2:1.2689705426548339,bias:-1.4461446330795382,loss:0.5557597323221762
Epoch:113,w1:1.7422493370011491,w2:1.2717259187468763,bias:-1.4541971277199894,loss:0.5551969752209972
Epoch:114,w1:1.7566408960302853,w2:1.2744298961510627,bias:-1.4622023081939515,loss:0.5546375118777875
Epoch:115,w1:1.7710118844916096,w2:1.2770834953494485,bias:-1.470160873220624,loss:0.5540812947428827
Epoch:116,w1:1.78536217039221,w2:1.2796877160553668,bias:-1.4780735081515395,loss:0.553528277707171
Epoch:117,w1:1.7996916253913906,w2:1.2822435376693875,bias:-1.4859408852566225,loss:0.5529784160480445
Epoch:118,w1:1.8140001247269388,w2:1.2847519197242308,bias:-1.4937636640033831,loss:0.552431666377507
Epoch:119,w1:1.8282875471430662,w2:1.2872138023189243,bias:-1.5015424913294295,loss:0.5518879865923448
Epoch:120,w1:1.8425537748199767,w2:1.2896301065424844,bias:-1.5092780019084795,loss:0.5513473358262798
Epoch:121,w1:1.8567986933050165,w2:1.292001734887398,bias:-1.5169708184100483,loss:0.5508096744040182
Epoch:122,w1:1.8710221914453602,w2:1.2943295716531706,bias:-1.5246215517529802,loss:0.5502749637971193
Epoch:123,w1:1.8852241613221923,w2:1.2966144833402033,bias:-1.5322308013529893,loss:0.5497431665816075
Epoch:124,w1:1.8994044981863423,w2:1.2988573190342478,bias:-1.5397991553643708,loss:0.5492142463972551
Epoch:125,w1:1.9135631003953337,w2:1.3010589107816908,bias:-1.5473271909160353,loss:0.5486881679084702
Epoch:126,w1:1.9276998693518088,w2:1.3032200739559034,bias:-1.5548154743420193,loss:0.5481648967667201
Epoch:127,w1:1.9418147094432912,w2:1.3053416076148925,bias:-1.5622645614066164,loss:0.547644399574428
Epoch:128,w1:1.9559075279832518,w2:1.3074242948504768,bias:-1.5696749975242716,loss:0.5471266438502863
Epoch:129,w1:1.9699782351534425,w2:1.3094689031292142,bias:-1.5770473179743765,loss:0.5466115979959221
Epoch:130,w1:1.9840267439474635,w2:1.3114761846252887,bias:-1.5843820481110977,loss:0.5460992312638665
Epoch:131,w1:1.9980529701155334,w2:1.3134468765455725,bias:-1.5916797035683712,loss:0.5455895137267694
Epoch:132,w1:2.0120568321104297,w2:1.3153817014470603,bias:-1.5989407904601847,loss:0.5450824162478126
Epoch:133,w1:2.026038251034569,w2:1.3172813675468789,bias:-1.6061658055762729,loss:0.5445779104522697
Epoch:134,w1:2.039997150588198,w2:1.3191465690250594,bias:-1.6133552365733441,loss:0.5440759687001709
Epoch:135,w1:2.0539334570186667,w2:1.3209779863202649,bias:-1.6205095621619525,loss:0.543576564060022
Epoch:136,w1:2.0678470990707574,w2:1.322776286418648,bias:-1.627629252289128,loss:0.5430796702835395
Epoch:137,w1:2.081738007938039,w2:1.3245421231360235,bias:-1.6347147683168735,loss:0.5425852617813608
Epoch:138,w1:2.0956061172152265,w2:1.3262761373935195,bias:-1.6417665631966343,loss:0.5420933135996872
Epoch:139,w1:2.1094513628515146,w2:1.3279789574868814,bias:-1.6487850816398424,loss:0.5416038013978256
Epoch:140,w1:2.1232736831048666,w2:1.3296511993495872,bias:-1.6557707602846348,loss:0.5411167014265906
Epoch:141,w1:2.137073018497231,w2:1.3312934668099337,bias:-1.6627240278588433,loss:0.5406319905075359
Epoch:142,w1:2.1508493117706635,w2:1.3329063518422464,bias:-1.66964530533935,loss:0.540149646012975
Epoch:143,w1:2.1646025078443376,w2:1.3344904348123643,bias:-1.6765350061078983,loss:0.5396696458467706
Epoch:144,w1:2.1783325537724116,w2:1.3360462847175427,bias:-1.683393536103449,loss:0.5391919684258498
Epoch:145,w1:2.1920393987027436,w2:1.3375744594209173,bias:-1.6902212939711703,loss:0.5387165926624278
Epoch:146,w1:2.2057229938364236,w2:1.3390755058806658,bias:-1.6970186712081394,loss:0.5382434979469025
Epoch:147,w1:2.219383292388112,w2:1.3405499603740014,bias:-1.7037860523058441,loss:0.5377726641314001
Epoch:148,w1:2.2330202495471587,w2:1.3419983487161278,bias:-1.7105238148895585,loss:0.5373040715139433
Epoch:149,w1:2.2466338224394873,w2:1.343421186474282,bias:-1.7172323298546717,loss:0.5368377008232168
Epoch:150,w1:2.2602239700902267,w2:1.3448189791769884,bias:-1.7239119615000453,loss:0.5363735332039089
Epoch:151,w1:2.273790653387073,w2:1.346192222518643,bias:-1.7305630676584702,loss:0.5359115502026047
Epoch:152,w1:2.287333835044363,w2:1.347541402559544,bias:-1.7371859998242951,loss:0.5354517337542094
Epoch:153,w1:2.3008534795678446,w2:1.348866995921484,bias:-1.7437811032782948,loss:0.5349940661688829
Epoch:154,w1:2.3143495532201275,w2:1.350169469979009,bias:-1.7503487172098453,loss:0.5345385301194635
Epoch:155,w1:2.3278220239867986,w2:1.3514492830464566,bias:-1.7568891748364712,loss:0.5340851086293615
Epoch:156,w1:2.3412708615431868,w2:1.3527068845608743,bias:-1.763402803520828,loss:0.5336337850609069
Epoch:157,w1:2.3546960372217653,w2:1.353942715260919,bias:-1.7698899248851805,loss:0.533184543104131
Epoch:158,w1:2.3680975239801727,w2:1.3551572073618379,bias:-1.776350854923439,loss:0.5327373667659668
Epoch:159,w1:2.3814752963698425,w2:1.356350784726626,bias:-1.7827859041108096,loss:0.5322922403598492
Epoch:160,w1:2.3948293305052255,w2:1.3575238630334518,bias:-1.7891953775111165,loss:0.5318491484957043
Epoch:161,w1:2.408159604033595,w2:1.3586768499394435,bias:-1.79557957488185,loss:0.531408076070308
Epoch:162,w1:2.4214660961054193,w2:1.3598101452409241,bias:-1.8019387907769961,loss:0.5309690082580021
Epoch:163,w1:2.4347487873452875,w2:1.3609241410301807,bias:-1.808273314647699,loss:0.5305319305017536
Epoch:164,w1:2.4480076598233844,w2:1.3620192218488498,bias:-1.8145834309408047,loss:0.5300968285045445
Epoch:165,w1:2.4612426970274925,w2:1.3630957648380044,bias:-1.8208694191953407,loss:0.5296636882210775
Epoch:166,w1:2.474453883835517,w2:1.364154139885016,bias:-1.827131554136975,loss:0.5292324958497893
Epoch:167,w1:2.48764120648852,w2:1.3651947097672745,bias:-1.8333701057705036,loss:0.5288032378251547
Epoch:168,w1:2.500804652564255,w2:1.3662178302928354,bias:-1.8395853394704123,loss:0.5283759008102747
Epoch:169,w1:2.513944210951187,w2:1.3672238504380725,bias:-1.8457775160695555,loss:0.5279504716897362
Epoch:170,w1:2.527059871822993,w2:1.368213112482402,bias:-1.851946891945999,loss:0.52752693756273
Epoch:171,w1:2.5401516266135293,w2:1.3691859521401517,bias:-1.8580937191080638,loss:0.5271052857364249
Epoch:172,w1:2.553219467992259,w2:1.3701426986896394,bias:-1.8642182452776168,loss:0.5266855037195786
Epoch:173,w1:2.566263389840126,w2:1.3710836750995268,bias:-1.8703207139716465,loss:0.5262675792163832
Epoch:174,w1:2.5792833872258716,w2:1.372009198152514,bias:-1.8764013645821607,loss:0.5258515001205356
Epoch:175,w1:2.5922794563827782,w2:1.3729195785664345,bias:-1.8824604324544492,loss:0.5254372545095194
Epoch:176,w1:2.6052515946858397,w2:1.3738151211128142,bias:-1.888498148963743,loss:0.5250248306390973
Epoch:177,w1:2.618199800629341,w2:1.3746961247329492,bias:-1.8945147415903092,loss:0.5246142169380005
Epoch:178,w1:2.6311240738048465,w2:1.3755628826515636,bias:-1.9005104339930181,loss:0.5242054020028113
Epoch:179,w1:2.6440244148795813,w2:1.3764156824881015,bias:-1.906485446081412,loss:0.5237983745930287
Epoch:180,w1:2.656900825575206,w2:1.3772548063657073,bias:-1.912439994086314,loss:0.5233931236263114
Epoch:181,w1:2.6697533086469694,w2:1.3780805310179483,bias:-1.9183742906290064,loss:0.5229896381738935
Epoch:182,w1:2.6825818678632376,w2:1.3788931278933303,bias:-1.9242885447890126,loss:0.5225879074561629
Epoch:183,w1:2.6953865079853867,w2:1.3796928632576575,bias:-1.9301829621705104,loss:0.5221879208383975
Epoch:184,w1:2.708167234748058,w2:1.3804799982942852,bias:-1.9360577449674112,loss:0.5217896678266553
Epoch:185,w1:2.7209240548397626,w2:1.3812547892023128,bias:-1.9419130920271295,loss:0.5213931380638096
Epoch:186,w1:2.7336569758838345,w2:1.3820174872927642,bias:-1.947749198913076,loss:0.5209983213257265
Epoch:187,w1:2.7463660064197177,w2:1.3827683390828014,bias:-1.9535662579658997,loss:0.520605207517577
Epoch:188,w1:2.7590511558845905,w2:1.3835075863880142,bias:-1.9593644583635075,loss:0.5202137866702806
Epoch:189,w1:2.771712434595313,w2:1.38423546641283,bias:-1.9651439861798856,loss:0.5198240489370745
Epoch:190,w1:2.7843498537306948,w2:1.3849522118390867,bias:-1.970905024442753,loss:0.519435984590204
Epoch:191,w1:2.796963425314075,w2:1.385658050912807,bias:-1.9766477531900684,loss:0.5190495840177303
Epoch:192,w1:2.8095531621962113,w2:1.3863532075292169,bias:-1.9823723495254164,loss:0.5186648377204487
Epoch:193,w1:2.8221190780384706,w2:1.387037901316046,bias:-1.9880789876722995,loss:0.5182817363089175
Epoch:194,w1:2.834661187296315,w2:1.3877123477151478,bias:-1.9937678390273557,loss:0.5179002705005886
Epoch:195,w1:2.8471795052030777,w2:1.388376758062476,bias:-1.999439072212527,loss:0.5175204311170399

(np.float64(5.04459551796092),
 np.float64(1.4573908077940547),
 np.float64(-2.9573139269051905))

In [38]:
coef,intercept

(array([[5.0608625],
        [1.408652 ]], dtype=float32),
 array([-2.9137027], dtype=float32))